### ISSUE TITLE
Simplex crashes instantly on launch

### ISSUE THREAD

**Issue by Elara6331** [SuperCoder7979/simplexterrain#21]
Simplex crashes instantly on launch in 1.16 snapshot 20w12a and 20w10a with error message:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'simplexterrain'!

Crash report:

[crash-2020-03-18_17.09.32-client.txt](https://github.com/SuperCoder7979/simplexterrain/files/4352008/crash-2020-03-18_17.09.32-client.txt)

**Comment by jaskarth** [comment]
It's a known issue, Simplex Terrain won't work on 20w11a or above until I release an update.

**Comment by Mackzwellz** [comment]
@SuperCoder7979 my crash log looks really similar to the one above, so positing in this issue.

[crash-2020-10-06_01.37.40-client.txt](https://github.com/SuperCoder7979/simplexterrain/files/5330199/crash-2020-10-06_01.37.40-client.txt)
